### ISSUE TITLE
astrostats and profiles

### ISSUE THREAD

**Issue by michael-petersen** [perwin/s4g_barfractions#1]
Two quick problems in s4gbars_main.ipynb: 

1. astrostat.Binomial, in GetBarazzaData, is not defined (looks like s4gutil.Binomial?)

2. profiles.ReadProfile is not defined (not sure which helper it is, couldn't find one in datautil.py that seemed to match)

[thanks for the work making these notebooks, they are awesome!]

**Comment by perwin** [comment]
Ouch -- thanks for catching these!

Yes, s4gutils.Binomial should work in place of "astrostat.Binomial"

profiles.ReadProfile should be s4gutils.Read2ColumnProfile.

I'll see about updating the repo with these corrections.

**Comment by perwin** [comment]
OK, I think the updated version of that notebook should have the proper module/function references now. If you get a chance to test it, let me know if it works!

**Comment by michael-petersen** [comment]
Works great, thanks! 

Only other hiccup I had was that reload() isn't compatible as a builtin with python3, but I didn't seem to need the reload anyway.

**Comment by perwin** [comment]
I think by default I have "from importlib import reload" in my pythonstart.py file, which is why I don't run into that particular problem (any more, anyway).

But that line in the notebook is, as you noted, completely unnecessary (one more bit of code left over from re-iterating on the notebook), so I'll take it out.

**Comment by perwin** [comment]
I'm going to go ahead and close this issue, but feel free to re-open it (or another one) if there are any lingering problems...
